### PR TITLE
[TECH-241] - Remove warning for missing eximstatspass for v11.64+

### PR DESCRIPTION
**Pull request by RickyGrassmuck**
Added a version check in the `check_for_eximstats_newline()` subroutine to prevent the warning from being given on servers running cPanel version 11.64 or newer.

Resolves [TECH-241].

### CODE REVIEW

**Review by cPanelChrisD — CHANGES_REQUESTED** [review]
One minor change I suggest is to check for "< 11.63.0.0" so that the 64 dev versions are included.

Can you please also run this through "/usr/local/cpanel/3rdparty/perl/524/bin/perltidy --profile=.perltidyrc ssp" using a copy of our perltidyrc which can be found [here](https://github.com/CpanelInc/cPanel-PublicAPI/blob/master/.perltidyrc)?  It will spit out 'ssp.tdy' which I suggest that you 'diff' with the original ssp first, and then overwrite if the changes look good.  SHA512SUM would need to be updated again.  I'll be adding a Makefile and the perltidyrc directly to the SSP repo to help with this, soon.

This is also going to tidy up the previous commit that was done for selinux status.

**Comment by RickyGrassmuck** [comment]
Sounds good, I'll make the changes when I get back in tonight.

**Comment by RickyGrassmuck** [comment]
@cPanelChrisD Should be good to go now.

**Review by cPanelChrisD — APPROVED** [review]
Looks good, and passes my testing.  Ready for @davelcpanelnet to do testing/merge.

**Pull request merged**
