### PR TITLE
[TECH-263] - Modify check_selinux_status to detect when in Permissive mode

### PR DESCRIPTION
**Pull request by cPanelRicky**
This pull request adds additional logic to the check_selinux_status subroutine to check if SELinux is Permissive or Enforcing when it detects that it is not strictly disabled.

We require SELinux to be disabled but SELinux will not affect cPanel when enabled and set to Permissive. 

Since most servers end up in Permissive mode, the old warning "SELinux: is NOT disabled"  is almost always displayed which means a manual lookup is needed to get the true state of SELinux.

### CODE REVIEW

**Review by cPanelChrisD — COMMENTED** [review]
About 2 years ago the check was intentionally simplified to "NOT disabled" because our documentation states that SELinux should be "disabled", not "permissive", and definitely not "enforcing".  Though permissive is functional, it is not recommended.

Old commit:
https://github.com/cPanelSSP/SSP/commit/21c824415f3ee7439ab948903c5b658d217e1a14#diff-97c9c694d99f729e1a48940d0b386a9bR2163

That said, I don't think the current check is entirely useful (it will be ignored because it is too noisy) and I like the idea of reporting "permissive" mode as info and not a warning, so I approve of this logic.

This commit does not meet other non-code-related requirements, please also see "Contributing to System Status Probe - SSP" wiki article.

**Comment by cPanelRicky** [comment]
Right, I may be alone in this but I often find myself overlooking that warning simply because it's nearly always given due to the majority of servers being set to permissive.

This check removes that ambiguity giving a precise output that ensures if SELinux is enforcing, the tech will know about it.

Fact is, permissive and enforcing are two very different situations and should not be lumped together as if they are off equal consequence.

I'll be sure to check out the contributing page when I get back in tonight.

Sent by Mailwise – Your emails, with style.:)
    

-------- Original Message --------

**Comment by RickyGrassmuck** [comment]
Derp, email only showed the paragraph before the old commit message, I'll make the fixes necessary to bring it up to snuff this evening.

**Comment by davelcpanelnet-zz** [comment]
Yes we really want to know if the system is set to anything other than what we advise.  I've seen cPanel systems do all sorts of crazy things if SELinux is not 100% disabled - which is why we make that recommendation.

**Comment by cPanelRicky** [comment]
@cPanelChrisD Updated the pull request to bring it in line with the standards as laid out in the wiki. I opened the JIRA case(TECH-263), merged the recent commits from upstream and squashed the conflicts, bumped the version number and updated the SHA512SUM file to include the new hash of ssp after all changes were made.

Let me know if there is anything else that needs to be done.

**Review by cPanelChrisD — APPROVED** [review]
These changes look good to me, and passes the tests I threw at it.

**Comment by davelcpanelnet-zz** [comment]
**TESTING STEPS**

1. I moved the system over to SELinux permissive.
```
[root@4a6d1a0a-f5dc-4ba5-9975-76f6ea1a068e ~]# perl -pi*.bak -e 's{SELINUX=disabled}{SELINUX=permissive}g;' /etc/selinux/config
```
```
[root@4a6d1a0a-f5dc-4ba5-9975-76f6ea1a068e ~]# awk '!/^$|^#/' /etc/selinux/config
SELINUX=permissive
SELINUXTYPE=targeted
```
```
[root@4a6d1a0a-f5dc-4ba5-9975-76f6ea1a068e ~]#  shutdown -r now
```
2. Assure it's fired up permissively
```
[root@4a6d1a0a-f5dc-4ba5-9975-76f6ea1a068e ~]# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      30
```
3. Check Commit
```
[INFO] * Mailserver: dovecot
[INFO] * FTP Server: pure-ftpd ( Passive ports enabled - not found in iptables )
[INFO] * Exim: 20 second SMTP delay active (by default) for unknown hosts and spam, see DOC-6092. Disabled for: [Greylisting Trusted Hosts]
[INFO] * License: 208.74.121.106 has [CloudLinux] [cPanel]
[INFO] * SELinux: Permissive
[WARN] * /etc/cpsources.conf: exists! This can affect upcp and EA.
[WARN] * dhclient: found in the process list
[WARN] * /var/cpanel/nocloudlinux: exists! CloudLinux cannot be installed when this file is present.
[WARN] * /var/cpanel/eximstatspass: missing!
[WARN] * Mod Ruid2: is incompatible with ModSecurity SecDataDir (collections) until EA-4093 is resolved.
RPM check (running "rpm -qa ..."). This will timeout after 25 seconds.
```
** The main line we are looking for**
```
[INFO] * SELinux: Permissive
```

**Pull request merged**
